### ISSUE TITLE
what is the purpose of the value and * input and output?

### ISSUE THREAD

**Issue by Duodecimus** [willblaschko/ComfyUI-Unload-Models#1]
I'm newish to comfyui, so it isn't immediately obvious how to use this node.

Say I had a model get loaded, produce an image, save the image, and then I want to unload the model.

Is the correct usage to link the outputted image into value?

Is * then a sort of 'done unloading!' event? How is that linked to future nodes?

**Comment by willblaschko** [comment]
Hello! These are passthrough nodes, so they sit in the chain where you want to force an unload. So if you want to do another process on the image you created (after saving), then you can use this to pass the image through to the second process while also unloading the model used to create the image. In theory, making space for the next model you need to load.

In this case, both the input and the output would be the same image. You can also pass through any other value (e.g. prompts, etc.). It's supposed to be pretty generic.

**Comment by willblaschko** [comment]
Closing as this should answer your question!

**Comment by Duodecimus** [comment]
It does, thank you!
